### ISSUE TITLE
Override default serializedName for Fields

### ISSUE THREAD

**Issue by jviney** [wvteijlingen/Spine#44]
Hi,

Thanks for the great work on Spine - it's fantastic :+1: .

The API I'm working with always uses underscored strings for serialization. Rather than specifying the serialized name every time with ```Attribute().serializedAs("underscored_name_here")``` I'd instead like to override or subclass ```Attribute``` to make this the default.

This seems tricky currently because none of the properties of the ```Field``` class are public, and hence can't be overridden or accessed from a subclass inside a my project.

Could the ```name``` and ```serializedName``` properties be made public? I'm happy to provide a patch. I also tried to provide a different implementation of ```fieldsFromDictionary```, but a similar problem exists because the ```name``` field is not accessible. Or perhaps there is a better way to do this?

I'm using the swift-2.0 branch.

Cheers.

**Comment by wvteijlingen** [comment]
This is good point. We could always make those variables public. I think it might be better however to implement some kind of global FieldNameSerialiser that takes care of converting names to their serialised names. That way you could configure this on the Spine instance instead of having to subclass.

**Comment by kurko** [comment]
Agree with @wvteijlingen. Inheritance is not the solution, but composition.

**Comment by aganov** [comment]
+1 for making `name` and `serializedName` public

**Comment by wvteijlingen** [comment]
I'm experimenting with a way to globally configure key formatting. You can find this in the [key-formatter branch](https://github.com/wvteijlingen/Spine/tree/key-formatter).

Instead of having to specify the serialised name for every attribute, you can now use a `UnderscoredKeyFormatter` and let Spine format al your fields for you:

```
spine.keyFormatter = UnderscoredKeyFormatter()
```

By default it uses the `DasherizedKeyFormatter` because dasherized keys are recommended by the JSON:API spec.

**Comment by jviney** [comment]
Just saw that this got merged - great stuff. The ```KeyFormatter``` initializer needs to be public though, otherwise you can't set a different key formatter.

I fixed this with:

```
extension KeyFormatter {
    public init() { self.init() }
}
```

**Comment by jviney** [comment]
Nice work. The KeyFormatter implementations need some public initialisers though.

**Comment by wvteijlingen** [comment]
Done!

**Comment by kurko** [comment]
:clap: :clap: :clap: :clap:
